services:
  builder:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./src:/app/src
      # This "plugs" Windows C: drive into the container's /mnt/c/ when using docker
      - /mnt/c/temp_test:/mnt/c/temp_test
    #prevents the container from exiting immediately if there's a minor error
    stdin_open: true
    tty: true
